# Generated by Django 4.2 on 2025-06-18 22:51

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WheelConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Çevirmek için gereken tutar', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WheelPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('prize_type', models.CharField(choices=[('product', 'Ürün'), ('balance', 'Bakiye'), ('discount', 'İndirim Kuponu'), ('premium', 'Premium Üyelik'), ('nothing', 'Boş')], max_length=20)),
                ('balance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_percentage', models.IntegerField(blank=True, help_text='İndirim yüzdesi', null=True)),
                ('premium_days', models.IntegerField(blank=True, help_text='Premium üyelik gün sayısı', null=True)),
                ('probability', models.DecimalField(decimal_places=2, help_text='Kazanma olasılığı (0.01-100.00)', max_digits=5)),
                ('max_daily_wins', models.IntegerField(default=0, help_text='Günlük maksimum kazanım (0 = sınırsız)')),
                ('max_total_wins', models.IntegerField(default=0, help_text='Toplam maksimum kazanım (0 = sınırsız)')),
                ('color', models.CharField(default='#FF6B6B', help_text='Hex renk kodu', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('wheel_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='wheel.wheelconfiguration')),
            ],
            options={
                'ordering': ['-probability'],
            },
        ),
        migrations.CreateModel(
            name='WheelSpin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spin_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_winner', models.BooleanField(default=False)),
                ('prize_delivered', models.BooleanField(default=False)),
                ('delivery_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wheel_spins', to='wheel.wheelprize')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wheel_spins', to=settings.AUTH_USER_MODEL)),
                ('wheel_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spins', to='wheel.wheelconfiguration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WheelSpinHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_spins', models.IntegerField(default=0)),
                ('total_winners', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_prizes_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('wheel_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wheel.wheelconfiguration')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'wheel_config')},
            },
        ),
    ]
